name: .NET

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore src
      - name: Build
        run: dotnet build src --no-restore
      - name: Test
        run: dotnet test src --no-build --verbosity normal
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
      - name: Docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: adnans/mahala/magalaapi:latest
          context: src
          file: src/Mahala.Api/Dockerfile
